### ISSUE TITLE
About dialog throws an error at app startup

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2624]
```
Uncaught (in promise) Error: Request getApplicationInfo failed with message: ENOENT: no such file or directory, open 'C:\Users\kittaakos\dev\MyApp\theia-app\electron-app\dist\win-unpacked\package.json'
    at Proxy.<anonymous> (proxy-factory.ts:230)
    at AboutDialog.<anonymous> (about-dialog.ts:49)
    at step (about-dialog.ts:15)
    at Object.next (about-dialog.ts:15)
    at about-dialog.ts:15
    at Promise (<anonymous>)
    at ./node_modules/@theia/core/lib/browser/about-dialog.js.__awaiter (about-dialog.ts:15)
    at AboutDialog../node_modules/@theia/core/lib/browser/about-dialog.js.AboutDialog.init (about-dialog.ts:45)
    at _postConstruct (instantiation.js:27)
    at Object.resolveInstance (instantiation.js:47)
```

 - This should not happen.
 - We incorrectly assume the location of the `package.json`.
 - Preferably, the about dialog should be initialized lazily.

Note: happens in a bundled electron application.

Related: #1837

**Comment by kittaakos** [comment]
Happens with the browser example too:
```
Uncaught (in promise) Error: Request getApplicationInfo failed with message: Cannot read property 'name' of undefined
    at Proxy.<anonymous> (bundle.js:101418)
    at AboutDialog.<anonymous> (bundle.js:82769)
    at step (bundle.js:82730)
    at Object.next (bundle.js:82711)
    at bundle.js:82705
    at new Promise (<anonymous>)
    at ../../packages/core/lib/browser/about-dialog.js.__awaiter (bundle.js:82701)
    at AboutDialog.../../packages/core/lib/browser/about-dialog.js.AboutDialog.init (bundle.js:82762)
    at _postConstruct (bundle.js:41631)
    at Object.resolveInstance (bundle.js:41651)
```

**Comment by akosyakov** [comment]
https://github.com/theia-ide/theia/issues/2624#issuecomment-421907900 should have been fixed by https://github.com/theia-ide/theia/commit/b6e09bdfbd672f149178f049c7518e34b9676db4

**Comment by kittaakos** [comment]
I do not see this in the browser version anymore. It is still present in the bundled electron.

I will look into this: 
 - First off, it should not populate the `AboutDialog` content at app startup.
 - It should respect electron and the location of the `package.json`.

**Comment by kittaakos** [comment]
It is pretty tricky. We should be able to recognize, we are running a bundled electron application. In such cases, we cannot just rely on `process.cwd` here:
https://github.com/theia-ide/theia/blob/fd9dfcaa30e77787d35fc63602baacd3fcf8ffda/dev-packages/cli/src/theia.ts#L55

But we have to append, `resources/app`. This is a forked process, and does not return with `true` is [checking whether we are in electron or not](https://github.com/cheton/is-electron/blob/master/index.js).
